/**
 * Unicode Confusables Data
 * Pre-loaded confusables data from Unicode Security Mechanisms (UTS #39)
 */

import type { ConfusableMap } from "../types";

// Import confusables data
// This will be generated by the update script
import confusablesData from "./confusables.json";

export const confusables: ConfusableMap = confusablesData as ConfusableMap;
